"""mig1

Revision ID: e9d066a89d69
Revises: b32d9ac27115
Create Date: 2025-07-20 13:47:20.964123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d066a89d69'
down_revision = 'b32d9ac27115'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
